### ISSUE TITLE
DDD Perth website does not load at all in Internet Explorer

### ISSUE THREAD

**Issue by battlepanda** [dddwa/dddperth-website#142]
Error output: An unexpected error has occurred.

**Comment by mzaatar** [comment]
Did a quick investigation and found it might be related to Babel and ES6. 
This could be the solution. didn't have time to try it: https://github.com/babel/babel-preset-env/issues/203#issuecomment-285820866
'[
![Screen Shot 2019-03-17 at 01 28 10](https://user-images.githubusercontent.com/4103517/54479288-3d0a8e00-4856-11e9-9344-bca36c173824.png)
](url)

**Comment by antonjb** [comment]
How much of a concern is IE for us now that you're unable to purchase tickets with how the Tito widget works?

**Comment by dariom** [comment]
I just spoke with someone from one of our Gold sponsors who uses IE as his primary browser. It's not a good look if the people supporting our event experience this.

**Comment by robdmoore** [comment]
We’ve taken the stance of not supporting it so far because we have low usage of IE according to google analytics.

The way I see it we have 3 options:

* Leave as-is - terrible experience when people use IE
* Add a warning message about using IE not being supported rather than the generic error page
* Figure our how to support IE

--


On 25 Jun 2019, at 12:17 pm, Dario Mratovich <notifications@github.com<mailto:notifications@github.com>> wrote:


I just spoke with someone from one of our Gold sponsors who uses IE as his primary browser. It's not a good look if the people supporting our event experience this.

**Comment by dariom** [comment]
Fair enough, deciding with data is great! I know we can't support every browser out there but it was awkward talking to a sponsor who couldn't browse the site.

At a minimum I'd suggest adding a warning message.

**Comment by antonjb** [comment]
Would be interested in seeing what the current usage is and making a decision on this issue.

**Comment by antonjb** [comment]
Going to close this as we really haven't bee supporting IE11 and not sure there's much reason to now.
