### ISSUE TITLE
Titles of talks still being truncated

### ISSUE THREAD

**Issue by ucichr** [dddwa/dddperth-website#424]
Voting: Talks with long titles are being truncated, even though there is space on the 3 lines of title for the talk title to fit. Observed on desktop chrome and mobile android.
![image](https://user-images.githubusercontent.com/38847700/169809439-71788d35-9ba2-41d3-8a58-850bcf474abf.png)
![image](https://user-images.githubusercontent.com/38847700/169809843-42485438-e773-41cd-9125-34fbea1cd560.png)

**Comment by bplowry** [comment]
Ooh interesting. I wonder if they're being truncated on the backend because we should be getting 5 lines.

`'People who think they are crazy enough to change the world are the ones who do even during a pandem'.length === 99` so it's conceivable we have a limit on the field in the database or something

**Comment by J-tt** [comment]
Looks like it's in CSS, there's a -webkit-line-clamp rule on the title element.

It is set to 5 lines however, so I'm not sure why it's truncating so early, regardless, it can be removed.

**Comment by bplowry** [comment]
It's definitely truncated before it hits that line-clamp rule. You can see that it ends with `pandem` in the API response. 

![image](https://user-images.githubusercontent.com/9972287/169944520-2d0215c9-b75e-4401-89f3-a8325eabd0cb.png)

If they were side-by-side this probably would have hit the 5 line limit, but since we changed layout that's _way_ less likely. We could remove the `-webkit-line-clamp`, but it wouldn't change anything

**Comment by bplowry** [comment]
The 100 char limit was imposed by Sessionize
