### ISSUE TITLE
Voting: Session structure isn't resused

### ISSUE THREAD

**Issue by aaronpowell** [dddwa/dddperth-website#90]
It seems that we have two types that represent how a `Session` is structured in the codebase, we have [`DddSession`](https://github.com/dddwa/dddperth-website/blob/master/components/dddAgendaPage.tsx#L9-L18) that is used for agenda pages but it's not reused in voting, [it's a different structure](https://github.com/dddwa/dddperth-website/blob/master/config/types.ts#L181-L189).

This means that we need to have two different API endpoints, one which returns sessions for voting, one which returns sessions for the agenda (or general session info).

I've created a swagger definition for the DDD Sydney API (https://github.com/dddsydney/dddapi/blob/master/.azurefunctions/swagger/swagger.json) and is leveraging the previously known API structure.

I'd prefer not to have multiple APIs that are essentially providing the same data.

**Comment by robdmoore** [comment]
As discussed on slack/teams this was a deliberate decision to provide a clean break from the past. I've exported our previous year agenda data as static json files so I can ignore the old structure/data going forward. That's actually why I called that class `DddSession` rather than `Session`.

I think there is a lot of redundancy in the old structure names and they also don't support multiple presenters as a first class concept hence the desire to make a clean break.

Re: sessions for voting vs sessions for agenda, I actually want them to be separate anyway since I have different behaviour and fields being returned for both (e.g. due to anonymous session voting). From a domain driven design perspective I'm calling the former Submissions and the latter Sessions.
